### PR TITLE
Fix motions to support async def

### PR DESCRIPTION
**Pull request by wlonk**
Let me know if there are any changes this calls for; I tend to avoid the very-magic mode in vim regexes, but I see that's not always the style here.

A cute animal picture for your trouble:

elephant

### CODE REVIEW

**Comment by diraol** [comment]
Hi @wlonk thanks for your contribution.

I'm not used to use `motion`, so I kindly ask you if you can provide me with a sample python code and a fast guide for me to check the differences before and after your contribution. =)

Usually, I would not ask for such things, but I have been very busy, and this will be the fastest way for me to review the PR and make the contribution available for the community!

Thanks!

**Comment by wlonk** [comment]
Sure thing! See the gist here: https://gist.github.com/wlonk/4fc811057c7c8ad31dcf3cb8985dede8

**Comment by diraol** [comment]
Thanks @wlonk !

But I wasn't able to make the following work... I'm not sure if I am doing something wrong of if I have some kind of conflicts between my own vim setup....

> And for text objects, any of v, c, d, etc and then iC to get the inside of a class, aC to get all around a class, iM to get the inside of a def (sync or async), and aM to get the outside of a def (sync or async). I tend to use v as it's least destructive, and clearly shows what the plugin identifies as "in" or "around".

**Comment by wlonk** [comment]
Hm, you might. I can't really speak to that.

If your cursor is inside the `def`, or the `class`, those combos (`vaC`, `viM`, etc) should select the appropriate text object.

**Comment by wlonk** [comment]
@diraol can I nudge you on this?

**Comment by diraol** [comment]
Hi @wlonk I have tried to reproduce it again and wasn't able. I mean, it did not work as expected.

If there are more people able to check with and without your patch and confirm that the behavior changed, it would be very helpful!

**Comment by wlonk** [comment]
@diraol I've updated the gist with clearer instructions, I hope this helps.

https://gist.github.com/wlonk/4fc811057c7c8ad31dcf3cb8985dede8

The intention of this patch is to allow functions written as `async def` to count for motions and as text objects. Without the patch, they are skipped over or cause errors. This is an issue for those of us working in Python 3.7.

**Comment by diraol** [comment]
Hi @wlonk !

First of all, thanks for updating the gist!

I think I was having issues with testing in a "clean" environment.
[I've worked in a Docker structure](https://github.com/python-mode/python-mode/issues/977) in order to be able to test python-mode in a cleaner environment, and, because of that, I was able to properly test your PR!

**Pull request merged**
