### PR TITLE
Update submodules

### PR DESCRIPTION
**Pull request by diraol**
Updated submodules:
  - astroid
  - autopep8
  - mccabe
  - pycodestyle
  - pydocstyle
  - pyflakes
  - pylama
  - pylint
  - rope
  - six

### CODE REVIEW

**Comment by cdleong** [comment]
I will test it out, then edit this comment with results.

**Comment by cdleong** [comment]
I got some errors.
* on submodule updating, which I fixed by recloning the repo, and 
* "unknown function: execute" on opening a python file, but only in debug mode (?)
* "invalid syntax" on f-strings `print(f"bob")`

# Errors on git submodule update: 
When I first tried to just update my existing python-mode folder I got this: 
```
git submodule update --init --recursive
Submodule path 'submodules/astroid': checked out '01a25f31962dd5017a141a6450859a7c1c82722d'
Submodule path 'submodules/autopep8': checked out '48662f6ab39c646cb31db1c7f95c67281b5be0a3'
Submodule path 'submodules/mccabe': checked out '55942cba66d39c39bd0d8425ee29822be16dfded'
Submodule path 'submodules/pycodestyle': checked out 'e91ef6e40f2be30f9af7a86a84255d6bdfe23f51'
Submodule path 'submodules/pydocstyle': checked out '37c00d8fa8e43119e038d7309a784b094bd482ad'
fatal: reference is not a tree: 6501af45203dfa3e2d422cfb3ebbecff853db47f
fatal: reference is not a tree: b299575f89d478bd57cfc588901e1bf87a20927d
Submodule path 'submodules/pylint': checked out '4612b667ce75c83a03bc009d0dd64cc2d0e73080'
Submodule path 'submodules/rope': checked out '7da56484e931d542a3a2faaed5cb48caf3b7c641'
Submodule path 'submodules/six': checked out 'd927b9e27617abca8dbf4d66cc9265ebbde261d6'
Unable to checkout '6501af45203dfa3e2d422cfb3ebbecff853db47f' in submodule path 'submodules/pyflakes'
Unable to checkout 'b299575f89d478bd57cfc588901e1bf87a20927d' in submodule path 'submodules/pylama'
```

I tested the code from the pull request by making a local branch like so:
```bash
git fetch origin pull/1005/head:test-update-submodules
git checkout test-update-submodules
git submodule update --init --recursive  # this gave the errors above.
```

I fixed this by deleting my python-mode folder and doing like so: 
```bash
git clone --recursive https://github.com/python-mode/python-mode
```

# Errors on file open 
I tried creating a test python file "bob.py" with `vim bob.py`

This gave me importerrors on opening the file. I tried various things to fix that, which also revealed the submodule checkout problems above. The importerrors (I believe it was unable to find "six"?) are resolved by recloning recursively.

I still get errors in debug mode now, but not normal mode: 
```bash
vim -i NONE -u ~/.vim/bundle/python-mode/debugvimrc.vim bob.py
```
that command gives me this: 
```vim
"bob.py" [New File]
Error detected while processing /home/leongcd/.vim/bundle/python-mode/ftplugin/python/pymode.vim:
line  239:
E117: Unknown function: execute
E116: Invalid arguments for function matchstr( execute( g:pymode_python . " from __future__ import print_function;" . " import os;import tempfile; marker='|';" . " print(marker,
 tempfile.gettempdir(), os.sep, " .        "'pymode_debug_file.txt', marker, sep='', end='')"), '|\zs.*\ze|')
E15: Invalid expression: matchstr( execute( g:pymode_python . " from __future__ import print_function;" . " import os;import tempfile; marker='|';" . " print(marker, tempfile.ge
ttempdir(), os.sep, " .        "'pymode_debug_file.txt', marker, sep='', end='')"), '|\zs.*\ze|')
```

It did not indicate the location of the log file in that output, or when I used :messages.

However, when I just do this I get no "unknown function" error

```bash
# this does not give errors.
vi bob.py  
```

## Things I have tried to fix the on-open error: 
* clearing cache like so:
```bash
# in the python-mode folder...
find . -type f -name '*.pyc' -delete && find . -type d -name '__pycache__' -delete
```

* git submodule update --init --recursive again

# f-strings are invalid?
When I create a test file "bob.py" and add the line `print(f"bob")` I get a message saying it's invalid. 

Here's what I see in `:message`
```vim
[Location List] CodeCheck <bob.py>                                                                                                                            1,1             All
Messages maintainer: Bram Moolenaar <Bram@vim.org>
Error detected while processing /home/leongcd/.vim/bundle/python-mode/ftplugin/python/pymode.vim:
line  239:
E117: Unknown function: execute
E116: Invalid arguments for function matchstr( execute( g:pymode_python . " from __future__ import print_function;" . " import os;import tempfile; marker='|';" . " print(marker,
 tempfile.gettempdir(), os.sep, " .        "'pymode_debug_file.txt', marker, sep='', end='')"), '|\zs.*\ze|')
E15: Invalid expression: matchstr( execute( g:pymode_python . " from __future__ import print_function;" . " import os;import tempfile; marker='|';" . " print(marker, tempfile.ge
ttempdir(), os.sep, " .        "'pymode_debug_file.txt', marker, sep='', end='')"), '|\zs.*\ze|')
"bob.py" [New] 0L, 0C written
"bob.py" 1L, 14C written
-------------------------------------------------------------------------------
pymode debug msg 1: check code
1553184916 ['pyflakes', 'pep8', 'mccabe'] []
1553184916 Namespace(abspath=False, concurrent=False, file_params={}, force=True, format='pycodestyle', hook=False, ignore=[], linters=[('pyflakes', <pylama.lint.pylama_pyflakes
.Linter object at 0x7f4a110efe80>), ('pep8', <pylama.lint.pylama_pycodestyle.Linter object at 0x7f4a111d4860>), ('mccabe', <pylama.lint.pylama_mccabe.Linter object at 0x7f4a111d
47f0>)], linters_params={}, options=None, paths=['/home/leongcd'], report=None, select=[], skip=[], sort=[], verbose=False) []
1553184916 Start code check:  [bob.py]
Checking params: {'ignore': set(), 'select': set(), 'skip': False, 'linters': []}
Run pyflakes {'builtins': '_'}
<traceback object at 0x7f4a0fb14b48>
SyntaxError invalid syntax (bob.py, line 1)
1553184916 Find errors:  [1]

```

# My System:

## My .vimrc is like so: 
```
 28 call pathogen#infect()
 29 call pathogen#helptags()
 30 syntax on
 31 filetype plugin indent on
 32
 33 " #############  vim completion  ################
 34 " Make Vim completion popup menu work just like in an IDE
 35 "http://vim.wikia.com/wiki/Make_Vim_completion_popup_menu_work_just_like_in_an_IDE
 36 :set completeopt=longest,menuone
 37 :inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
 38
 39 " ############  Python-Mode settings  ##########
 40
 41 " python 3 please
 42 let g:pymode_python = 'python3'
 43
 44 " ### Linting/ Code-checking ###
 45
 46 " Turn it on
 47 let g:pymode_lint = 1
 48
 49 " Check code on every save, even if unmodified
 50 let g:pymode_lint_unmodified = 1
 51
 52 " don't bug me about 'line too long'
 53 let g:pymode_lint_ignore = ["E501"]
 54
 55 " Check code when editing (on the fly)
 56 let g:pymode_lint_on_fly = 1
 57
 58 " ### Rope ###
 59 " Turn on the rope script
 60 let g:pymode_rope = 1
 61
 62 " Enable searching for |.ropeproject| in parent directories
 63 let g:pymode_rope_lookup_project = 1
 64
 65 " turn on resolve import for element under cursor
 66 let g:pymode_rope_autoimport=1
 67
 68 " Regenerate project cache on every save (if file has been modified)
 69 let g:pymode_rope_regenerate_on_write = 1
 70
 71 " Show documentation for object under cursor. ctrl+c, then d
 72 let g:pymode_rope_show_doc_bind = '<C-c>d'
```

## ViM info: 
```
vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
Included patches: 1-1689
Extra patches: 8.0.0056
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
+balloon_eval    +float           +mouse_urxvt     +tcl
+browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
+clientserver    +iconv           +packages        +toolbar
+clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             +perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     +xsmp_interact
+emacs_tags      +mouseshape      +startuptime     +xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    +xpm
+extra_search    -mouse_jsbterm   +syntax
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -D_REENTRANT -DORBIT2=1 -pthread -I/usr/include/libgnomeui-2.0 -I/usr/include/gnome-keyring-1 -I/usr/include/libbonoboui-2.0 -I/usr/include/libxml2 -I/usr/include/libgnome-2.0 -I/usr/include/libbonobo-2.0 -I/usr/include/bonobo-activation-2.0 -I/usr/include/orbit-2.0 -I/usr/include/libgnomecanvas-2.0 -I/usr/include/gail-1.0 -I/usr/include/libart-2.0 -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/gnome-vfs-2.0 -I/usr/lib/x86_64-linux-gnu/gnome-vfs-2.0/include -I/usr/include/gconf/2 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E  -Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lgnomeui-2 -lSM -lICE -lbonoboui-2 -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lORBit-2 -lgnomecanvas-2 -lart_lgpl_2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lgdk_pixbuf-2.0 -lgnomevfs-2 -lgconf-2 -lgthread-2.0 -lgmodule-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.22/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu -lpython3.5m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lieee -lm -lruby-2.3 -lpthread -lgmp -ldl -lcrypt -lm
```

I have the following apt packages installed: 
```bash
apt list |grep vim|grep installed

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

vim/xenial-updates,xenial-security,now 2:7.4.1689-3ubuntu1.2 amd64 [installed]
vim-athena-py2/xenial-updates,xenial-security,now 2:7.4.1689-3ubuntu1.2 amd64 [installed,automatic]
vim-common/xenial-updates,xenial-security,now 2:7.4.1689-3ubuntu1.2 amd64 [installed]
vim-gnome/xenial-updates,xenial-security,now 2:7.4.1689-3ubuntu1.2 amd64 [installed,automatic]
vim-gui-common/xenial-updates,xenial-updates,xenial-security,xenial-security,now 2:7.4.1689-3ubuntu1.2 all [installed,automatic]
vim-runtime/xenial-updates,xenial-updates,xenial-security,xenial-security,now 2:7.4.1689-3ubuntu1.2 all [installed,automatic]
vim-tiny/xenial-updates,xenial-security,now 2:7.4.1689-3ubuntu1.2 amd64 [installed]

```

## My python info: 
```bash
> python --version
Python 2.7.12
> python3 --version
Python 3.5.2
> which python
/usr/bin/python
> which python3
/usr/bin/python3
```

**Comment by cdleong** [comment]
Tried various things to try and get syntax checking to work with f-strings, and keep getting different errors between debug and normal file opening. I have tried activating and deactivating my conda environment, and also editing the let g:pymode_python= setting, and both debug and normal file open commands. I keep getting errors. Table of results: 

| .vimrc g:pymode_python=...          | conda env active? | result (vi bob.py)                                                                             | result (vi -i ... bob.py)                                                                                  |
|-------------------------------------|-------------------|------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------|
| python3                             | no                | No error on file open, pylama syntax error on save                                              | Error on file open ("unknown function"), pylama syntax error on save, but only after altering the file.     |
| python3                             | yes               |  same as above                                                                                 | same as above                                                                                              |
| python                              | no                |  Errors on both file open ("pymode#init")and file save (code check not available)              | Error on file open ("unknown function") pylama syntax error on save, yes but only after altering the file. |
| python                              | yes               | same as above                                                                                  | same as above                                                                                              |
| /home/leongcd/miniconda3/bin/python | no                |  Error on file open ("pymode#init"),  but nothing happens on save, and no new messages appear. | Error on file open ("unknown function") pylama syntax error on save, yes but only after altering the file. |
| /home/leongcd/miniconda3/bin/python | yes               | same as above                                                                                  | same as above                                                                                              |


## "unknown function error" 
example: 
```vim
Error detected while processing function pymode#init:
line    2:
E319: Sorry, the command is not available in this version: python import sys, vim
line    3:
E319: Sorry, the command is not available in this version: python sys.path.insert(0, vim.eval('a:plugin_root'))
line    4:
E319: Sorry, the command is not available in this version: python sys.path = vim.eval('a:paths') + sys.path
Error detected while processing /home/leongcd/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:
line    3:
E319: Sorry, the command is not available in this version: python from pymode.virtualenv import enable_virtualenv
Error detected while processing function pymode#breakpoint#init:
line    9:
E319: Sorry, the command is not available in this version: python << EOF
line   11:
E492: Not an editor command: from pymode.libs.six import PY3
line   13:
E121: Undefined variable: PY3
E15: Invalid expression: PY3:
line   17:
E488: Trailing characters: else:
line   20:
E488: Trailing characters:         try:
line   31:
E170: Missing :endfor
```


## "pymode#init" error 

Example. This is with pymode_python set to the long path, no conda env activated, and using the plain vi command instead of debug mode:
```vim
Error detected while processing function pymode#init:
line    2:
E121: Undefined variable: import
E15: Invalid expression: import sys, vim
line    3:
E121: Undefined variable: sys
E15: Invalid expression: sys.path.insert(0, vim.eval('a:plugin_root'))
line    4:
E121: Undefined variable: sys
E15: Invalid expression: sys.path = vim.eval('a:paths') + sys.path
Error detected while processing /home/leongcd/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:
line    3:
E121: Undefined variable: from
E15: Invalid expression: from pymode.virtualenv import enable_virtualenv
Error detected while processing function pymode#breakpoint#init:
line    9:
E15: Invalid expression: << EOF
E15: Invalid expression: << EOF
line   11:
E492: Not an editor command: from pymode.libs.six import PY3
line   13:
E121: Undefined variable: PY3
E15: Invalid expression: PY3:
line   17:
E488: Trailing characters: else:
line   20:
E488: Trailing characters:         try:
line   31:
E170: Missing :endfor

```


## "code check not available" error 
These examples are with conda env activated, pymode_python='python',  plain 'vi bob.py' command
There's two parts to this one:

1. On loading a file...
```
Error detected while processing /home/leongcd/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
E319: Sorry, the command is not available in this version: python from pymode.lint import code_check

```

2. and on saving a file.
```vim
Error detected while processing function pymode#buffer_post_write[10]..pymode#lint#check:
line   11:
E319: Sorry, the command is not available in this version: python code_check()
```

**Comment by diraol** [comment]
I've updated the submodules again, now considering only python3. Some of the updated submodules may work with python2, or may not.

I've added the `0.10.0` tag that will be the last one to support python2.

From now on my idea is to support officially only python3. And this will probably be the first change towards such goal. 

So, tests here are very welcome!

Btw @zcodes, can you provide us with your "bob.py" that you have used to test?
Also, thank you for the very very impressive report! =)

**Comment by zcodes** [comment]
@diraol I have no bob.py, and this is reported by @cdleong

**Comment by cdleong** [comment]
@diraol happy to help: bob.py was just a blank new file I created. Could have been named anything, like foo.py or bar.py.

**Comment by diraol** [comment]
Ops! sorry guys! You two are the ones collaborating more with the project and I made a confusion without looking up with who I was talking to.

@cdleong Oh, I thought there was some python code over there. =)

Anyway, any feedback from both of you would be very welcome!

**Comment by diraol** [comment]
Droping this PR to make it again, now without python2 support

**Pull request closed without merging**
