### PR TITLE
Remove dead keywords and builtins; add match, case

### PR DESCRIPTION
**Pull request by NeilGirdhar**

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
I was extremely confused by the syntax highlighting of `apply`, and wondered if it might be some new Python feature—only to realize that it's a dead feature.  Hopefully, this will help other developers be less confused going forward.

**Comment by NeilGirdhar** [comment]
@diraol Would it be possible to take a quick look at this?  Muito obrigado

**Comment by diraol** [comment]
Hi @NeilGirdhar I'll try to take a look during this week (no promises).

But, in order to help me reviewing this PR, can you check in which python version were those keywords removed from python?

**Comment by NeilGirdhar** [comment]
@diraol Sounds great, thanks.

>  can you check in which python version were those keywords removed from python?

I'll make a table for you today.

**Comment by NeilGirdhar** [comment]
Removed in Python 3.0: basestring, unicode, unichr, basestring, long, file, apply, cmp, coerce, intern, xrange, raw_input, reduce, reload, StandardError, VMSError.

Added in Python 2.3: `__loader__`
Added in Python 3.0: `__annotations__`
Added in Python 3.2: `__cached__`
Added in Python 3.4: `__spec__`
Added in Python 3.10: match/case.

Hope this helps!

**Comment by diraol** [comment]
> Removed in Python 3.0: basestring, unicode, unichr, basestring, long, file, apply, cmp, coerce, intern, xrange, raw_input, reduce, reload, StandardError, VMSError.
> 
> Added in Python 2.3: `__loader__` Added in Python 3.0: `__annotations__` Added in Python 3.2: `__cached__` Added in Python 3.4: `__spec__` Added in Python 3.10: match/case.
> 
> Hope this helps!

Sure it does! Thanks for it :)

**Pull request merged**
