### PR TITLE
Remove pythonDot highlight match

### PR DESCRIPTION
**Pull request by zhimsel**
When the `cursorcolumn` or `cursorline` vim option is set, _any_ `.` characters result in the highlighting being set to `Normal` (instead of blank). This means that the "highlighted" line (via `cursorline`) is broken over the period. Please see attached screenshot for an example:

screen shot 2018-07-27 at 14 10 06

As far as I can tell, the `pythonDot` match doesn't really do anything except drop the highlighting back to `Normal` in a `pythonDottedName` match. This just seems useless, so I think we should just remove it and let the dots have the same highlight as the rest of the `pythonDottedName` matches.

The main reason for this PR was not for a specific issue (my highlighting issue was just a symptom). I submitted this PR because I noticed that the `pythonDot` highlight group seemed entirely pointless. All it does is drop the highlighting for any `.` characters to `Normal`. This doesn't seem to be expected or desired behavior (the `.` should match the surrounding highlight).

### CODE REVIEW

**Comment by diraol** [comment]
@zhimsel sorry not giving a feedback before.

I've tested over here in a clean environment, and I was not able to reproduce the behavior you described. I mean, I've tested with only `python-mode` and `vim-colorschemes` plugins and the highlight worked as expected.

Are you sure that there isn't any other plugins/configs interacting in your environment? Which theme are you using? solarized-dark?

**Comment by zhimsel** [comment]
> Are you sure that there isn't any other plugins/configs interacting in your environment?

It's quite possible. I can do some reductive testing to see if any other plugins are interfering when I get the time. I'll report back here once I've had the chance.

> Which theme are you using? solarized-dark?

Yes, solarized-dark.

**Comment by diraol** [comment]
Thanks @zhimsel !
I'm using a docker-environment to test python-mode. You can give it a try to start from a cleaner env without messing up with your own.
You can find more info about it here:
https://github.com/python-mode/python-mode/issues/977

**Comment by zhimsel** [comment]
@diraol I was able to do some more verification of this issue.

Using the following vimrc with neovim `0.3.4`:
```vim
source ~/.vim/vim-plug/plug.vim  " managed externally
call plug#begin('~/.vim/plugins')
  Plug 'altercation/vim-colors-solarized'
  Plug '~/dev/python-mode',
call plug#end()

" Set color scheme
silent! colorscheme solarized

set cursorline " Highlight current line
syntax enable " Enable syntax highlighting

" show highlight group for what's under the cursor
map <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```
I confirmed that the `.` is de-highlighted in the current line with `cursorline` set. I also tested the `flazz/vim-colorscheme` version of solarized.

---

The main reason for this PR was not for a specific issue (my highlighting issue was just a symptom). I submitted this PR because I noticed that the `pythonDot` highlight group seemed entirely pointless. All it does is drop the highlighting for any `.` characters to `Normal`. This doesn't seem to be expected or desired behavior (the `.` should match the surrounding highlight).

**Comment by diraol** [comment]
Hum... got it!

Well, I could not reproduce it, not even with your suggestion under a clean env (dockerized).

But the proposed changes seems to be reasonable after all (now that you explained the reason behind it).
So I'll merge and if someone faces issues with it, a new issue can be opened, and we can discuss it better. =)  Thanks for the contribution!

**Comment by zhimsel** [comment]
No problem! Thanks for merging!

**Pull request merged**
