### PR TITLE
Fix/import imp

### PR DESCRIPTION
**Pull request by dendisuhubdy**
Adding changes to address `imp` deprecated since version 3.4. https://docs.python.org/3/library/imp.html

### CODE REVIEW

**Comment by diraol** [comment]
@dendisuhubdy why did you closed the PR? Any special reason?!

**Comment by dendisuhubdy** [comment]
@diraol it didn't pass travis-ci build tests, I could reopen it if you want, and I didn't have time to resolve the conflicts (yet).

**Comment by diraol** [comment]
@dendisuhubdy try rebasing your branch against our `develop` branch, please! =)

**Comment by diraol** [comment]
@dendisuhubdy did you created this branch based on the `master` branch?

**Comment by dendisuhubdy** [comment]
@diraol I think so, I'm doing a reset --hard to the latest commit on the latest commit and rebasing it now

**Pull request closed without merging**
