### PR TITLE
Show linters error list only if not empty

### LINKED ISSUE #739: I get red warning from linter even if I have 0 issues found
```
:call pymode#lint#check()
[Pymode] Found errors and warnings: 0
```

It's not a big deal, since it says that it did not find any problems, but I have lint on save enabled, and the message being red it makes me check every-time.

https://github.com/python-mode/python-mode/blob/da4bfe5a409cebc4bd79d0d68c2f0a68b2d6c598/autoload/pymode/lint.vim#L62

It looks like the message should be different when no errors are found

### PR DESCRIPTION
**Pull request by glujan**
Resolve #739 as suggested by @kevinkjt2000

### CODE REVIEW

**Comment by glujan** [comment]
Test failures tear down:
1. `pymode check code lint new`
  This one is failing because `PymodeLint` is reading file content from a buffer and not from file system ([here](https://github.com/python-mode/python-mode/blob/d113cffc3f7a48564aeb568e1c7a6f5312ff09f5/pymode/lint.py#L61)). Should I change behaviour of this test?

2. `pymode check code lint code`
  A different output because pylint is used instead of pyflakes for some reason.

3. `pymode-plugin pymode save`
  I don't know the reason of failure (yet).

Is fixing those tests a priority?

**Comment by fmv1992** [comment]
Actually can you help me get those tests running? Never got the exact gist of it...

**Comment by glujan** [comment]
I can give it a shot. I'll ping you on Slack in case of any questions

**Comment by diraol** [comment]
Hi @glujan can you please rebase your PR branch against our develop branch and then see if the tests are passing?

**Comment by glujan** [comment]
@diraol Here you go, the branch is rebased and tests are green.

**Pull request merged**
