### PR TITLE
fixed auto insert for rope complete

### PR DESCRIPTION
**Pull request by zcodes**
when define simple class like:

```python
class Foo:
    def __init__(self, name):
        self.{cursor_here}
```
it will auto insert first complete item and `__init__` will insert here. this is annoying for i just want code `self.name`.

the complete behaviour should respect the user's config of vim option &completeopt. In vim's docs, &completeopt has 'noselect' and 'noinsert' option, so it should worked here.

this pr related to #689 #782

### CODE REVIEW

**Comment by diraol** [comment]
@zcodes is it going to keep the current behavior?

Can you add some docs about it (or point me to the docs that state that this is the expected behavior), please? =)

**Comment by zcodes** [comment]
@diraol the docs in vim is `:h 'completeopt'`, vim has many flags of option `&completeopt`, the flags like `menu`, `menuone`, `noinsert`, `noselect` and so on control the autocomplete behaviour.

e.g. if the `set completeopt=menu`, and there's only one possible completions, the vim will not popup a menu and just insert the completions, this like auto insert `__init__` describe above, user there's no chance to confirm the completions they want or not. 

but if `set completeopt=menuone,noinsert`, vim will popup menu also when there is only one match. for case above, vim will popup a menu with one completion item `__init__` and let user choose insert it or escape, if add `noselect` with `&completeopt`, vim will even not selected the first completion item.

i think here should following the vim api and respecting the user's configuration.

**Comment by diraol** [comment]
Hi @zcodes, thanks for the explanation, I completely agree with you!

I have only one more concern.

This will change python-mode behavior, right?
Because of that, we will impact our users directly after they update the plugin.

So, It would be nice to:

1. Add this comment/description you wrote above into the commit.
2. Add a note about it in python-mode docs.

Oh, just one more thing (this is a stylish thing from my side). Can we avoid "anonying" word in the commit message? ;)

**Comment by zcodes** [comment]
@diraol I rewrite the commit message, but I have no idea how to change the python-mode doc, can you help ?

**Comment by diraol** [comment]
Probably [here](https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt#L477)? or [here](https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt#L703)?

**Comment by zcodes** [comment]
@diraol is 344502c ok ?

**Comment by diraol** [comment]
Just perfect @zcodes ! Thank you very much! =)

Do you want to add yourself to the AUTHORS list in this PR?

**Comment by zcodes** [comment]
@diraol Thanks, but it doesn't matter.

**Pull request merged**
