### PR TITLE
Don't display in_hierarchy options that are not relevant to the current refactoring operation

### PR DESCRIPTION
**Pull request by lieryan**
Currently, when doing a refactoring operation, python-mode often display this four options:

```
[Pymode] Choose what to do:
1. perform
2. preview
3. perform in class hierarchy
4. preview in class hierarchy
Type number and <Enter> or click with the mouse (q or empty cancels): 
```

In many of the operations, 3 and 4 doesn't really do anything different than 1 and 2 and it's rather difficult to remember which operations you can actually do in_hierarchy with and which ones doesn't. 

With this PR, we don't show these extraneous operations when they are not relevant for the current refactoring operation. 

```
[Pymode] Choose what to do:
1. perform
2. preview
Type number and <Enter> or click with the mouse (q or empty cancels): 
```

### CODE REVIEW

**Comment by diraol** [comment]
Hi @lieryan sorry for the **very** long time to review it.
Can you post here a sample code and instructions for us to test it?

**Comment by lieryan** [comment]
Hi @diraol, thanks for looking into this. The changed behavior here does not actually depend on the text on the Vim buffer, so it shouldn't matter what the code you have on the python file for testing this change. In any case, in the places where I've removed the in-hierarchy option, currently python-mode never passes those options to rope anyway ([for example](https://github.com/python-mode/python-mode/pull/1143/files#diff-58f24d25400af7734ca9c4c35f0e6e7dd22adf3bd87a71cbbb7fec7426bd71fdR565-R571)).

If you want a code sample that demonstrates what the in_hierarchy does though, it basically changes how rope finds members of a class that belongs to a class inheritance hierarchy:

```python
class Fruit(abc.ABC):
    def eat(self):
        pass

class Apple(Fruit):
    def eat(self):
        pass

class Orange(Fruit):
    def eat(self):
        pass
```

When `in_hierarchy=True`, when renaming `Orange.eat()`, both `Fruit.eat()`, `Apple.eat()`, are considered the "same" symbol, so they're renamed as well. Otherwise, when `in_hierarchy=False`, only symbols that refers to `Orange.eat()` are renamed.

**Comment by diraol** [comment]
👋🏽 
Let's try to move with this one too!
This seems to be an easy conflict to handle.

**Comment by lieryan** [comment]
Hi @diraol, thank you for looking into these PRs, I've updated this one against the latest develop and addressed the merge conflicts.

**Review by diraol — APPROVED** [review]

**Pull request merged**
