### PR TITLE
Add highlight for regex metacharacters in rawstring

### PR DESCRIPTION
**Pull request by qifei9**
Without highlight for metacharacters, it is hard to write and read regex in code like:
```python
pattern = re.compile(r'^regex\td\d{2,3}\s\d+\n$')
```

### CODE REVIEW

**Comment by fmv1992** [comment]
I'll take a look as soon as I have time.

Did you get this code from somewhere? We are looking for 'outsourcing' our code as much as possible.

**Comment by qifei9** [comment]
The code was got from https://github.com/edliaw/vim-python and I made some modifications.

Whether it's OK to include this code into python-mode?

**Comment by fmv1992** [comment]
I have to check for the license but the primary idea here is that since python-mode is an amalgam of projects that we do not 'copy paste'  code files into our project and rather track them by a more efficient method.

I'll take a look into those details later (and probably merge the commit)!
Thanks for your help! : )

**Comment by alphaCTzo7G** [comment]
Seems like the repository `vim-python` is an imporovement over the original `python.vim` script that provided the syntax highlighting.

Some more recent scripts for syntax highlighting: 

1. https://github.com/vim-python/python-syntax
2. https://github.com/hdima/python-syntax
3. https://github.com/sheerun/vim-polyglot

**Pull request closed without merging**
