### PR TITLE
Drop Python 2 support

### LINKED ISSUE #935: RFC: Python versions support
Hi `python-mode` community!

Maintaining multiple compatible python versions has demanded huge efforts for us.

Many python projects already decided to stop supporting python2.7, since its EOL is scheduled to a quite close date. It has been receiving only security updates and bug fixes.

Even python [3.4](https://www.python.org/dev/peps/pep-0429/) and [3.5](https://www.python.org/dev/peps/pep-0478/) versions are receiving mainly security updates and bug fixes, with no expected new features implemented.

So, I would like to propose that we do a "final 2.7" release, supporting python 2.7 to the best that we can, and then shift for supporting only python3.

Even for python 3, since 3.6 is retro-compatible with the previous 3 versions, we may also think about support 3.6+ or 3.5+ (I am not fully sure about which is the best choice here).

So, my proposal is:

Do some final work by updating some of our dependencies with support to python 2.7, create a branch/TAG and a Release for this version.

Work on an updated version of python-mode with support to python 3.X+.
By doing that, we will be able to drop other dependencies, such as `pylama` (which is unmaintained) that can be replaced by `yala` (#841) or `proscpector` (#934).

What do you all think about it?

### LINKED ISSUE #1045: imp module is deprecated in favour of importlib
Error detected while processing function pymode#breakpoint#init:
line 27:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

Seems that the breakpoint.vim file uses an import that throws a python depreciation error.

### PR DESCRIPTION
**Pull request by avacariu**
This PR drops support for Python 2 by removing all if/else and try/except blocks related to handling differences between Python 2 and 3. Instead, it's just assumed that Python 3 is being used. 

It also removes the `six` submodule, which I'm assuming is safe because nothing's broken for me. If it's a dependency of another submodule, then I can remove that commit.

Fixes #935
Fixes #1045

### CODE REVIEW

**Comment by avacariu** [comment]
I didn't remove the Python 2 support from `pymode/autopep8.py` because that's a third-party library, and it should probably be replaced with a submodule: https://github.com/hhatto/autopep8

**Comment by diraol** [comment]
Hey @avacariu, thanks for you contribution!
I'll try to take a look and review it in the following two weeks.

But if other people can review it and try it would be great too, I think we need more than one reviewer here ;)

**Comment by diraol** [comment]
Oh, and I think that if we can go without `six` it is indeed better!

**Comment by diraol** [comment]
I've reviewed it and it seems to be working (tested locally, but not extensively).

Thanks @avacariu!
I'll remove some other stuff that I think can be purged, but will do it in another PR ;)

**Comment by avacariu** [comment]
Thanks @diraol!

**Pull request merged**
